import {box,copy,pretty} from './utils.js';
const app=document.querySelector('#app'),nav=document.querySelector('#nav');
const tools={
codec:{name:'01 CODEC',html:`<div class="notice">Processing stays in your browser.</div><div class="grid"><div class="field"><label>Input</label><textarea id="i"></textarea></div><div class="field"><label>Output</label><textarea id="o" readonly></textarea></div></div><div class="actions"><button class="btn" id="b">BASE64</button><button class="btn" id="h">HEX</button><button class="btn" id="u">URL</button><button class="btn alt" id="c">COPY</button></div>`,bind:r=>{let o=r.querySelector('#o');r.querySelector('#b').onclick=()=>o.value=btoa(unescape(encodeURIComponent(r.querySelector('#i').value)));r.querySelector('#h').onclick=()=>o.value=[...new TextEncoder().encode(r.querySelector('#i').value)].map(x=>x.toString(16).padStart(2,'0')).join('');r.querySelector('#u').onclick=()=>o.value=encodeURIComponent(r.querySelector('#i').value);r.querySelector('#c').onclick=()=>copy(o.value)}},
hash:{name:'02 HASH',html:`<div class="field"><label>Hash / digest</label><input id="h" placeholder="Paste a digest"></div><div class="actions"><button class="btn" id="a">IDENTIFY</button></div><div id="r"></div>`,bind:r=>r.querySelector('#a').onclick=()=>{let h=r.querySelector('#h').value.trim(),m={32:'MD5 / NTLM',40:'SHA-1',56:'SHA-224',64:'SHA-256',96:'SHA-384',128:'SHA-512'};r.querySelector('#r').innerHTML=box(`Length: ${h.length}\nPossible type: ${m[h.length]||'Unknown/common format not detected'}`)}},
password:{name:'03 PASSWORD',html:`<div class="field"><label>Password strength</label><input id="p" type="password"><meter id="m" min="0" max="100" value="0"></meter></div><div id="r"></div>`,bind:r=>r.querySelector('#p').oninput=e=>{let p=e.target.value,s=Math.min(100,p.length*4+(/[a-z]/.test(p)?15:0)+(/[A-Z]/.test(p)?15:0)+(/\d/.test(p)?15:0)+(/[^A-Za-z0-9]/.test(p)?20:0));r.querySelector('#m').value=s;r.querySelector('#r').innerHTML=box(`Score: ${Math.round(s)}/100\nLength: ${p.length}`)}},
jwt:{name:'04 JWT',html:`<div class="field"><label>JWT</label><textarea id="j"></textarea></div><div class="actions"><button class="btn" id="d">DECODE</button></div><div id="r"></div>`,bind:r=>r.querySelector('#d').onclick=()=>{try{let p=r.querySelector('#j').value.split('.'),d=x=>JSON.parse(atob(x.replace(/-/g,'+').replace(/_/g,'/')));r.querySelector('#r').innerHTML=box(JSON.stringify({header:d(p[0]),payload:d(p[1])},null,2))}catch(e){r.querySelector('#r').innerHTML=box('Invalid JWT: '+e.message)}}},
url:{name:'05 URL',html:`<div class="field"><label>URL</label><textarea id="u"></textarea></div><div class="actions"><button class="btn" id="p">PARSE</button></div><div id="r"></div>`,bind:r=>r.querySelector('#p').onclick=()=>{try{let x=new URL(r.querySelector('#u').value);r.querySelector('#r').innerHTML=box(JSON.stringify({protocol:x.protocol,host:x.host,path:x.pathname,query:Object.fromEntries(x.searchParams)},null,2))}catch{r.querySelector('#r').innerHTML=box('Invalid URL')}}},
json:{name:'06 JSON',html:`<div class="field"><label>JSON</label><textarea id="j"></textarea></div><div class="actions"><button class="btn" id="p">PRETTY</button><button class="btn alt" id="m">MINIFY</button></div><div id="r"></div>`,bind:r=>{r.querySelector('#p').onclick=()=>{try{r.querySelector('#r').innerHTML=box(pretty(r.querySelector('#j').value))}catch(e){r.querySelector('#r').innerHTML=box('Invalid JSON: '+e.message)}};r.querySelector('#m').onclick=()=>{try{r.querySelector('#r').innerHTML=box(JSON.stringify(JSON.parse(r.querySelector('#j').value)))}catch(e){r.querySelector('#r').innerHTML=box('Invalid JSON: '+e.message)}}}},
uuid:{name:'07 UUID',html:`<div class="actions"><button class="btn" id="g">GENERATE UUID V4</button><button class="btn alt" id="c">COPY</button></div><pre class="out" id="r"></pre>`,bind:r=>{let v='';r.querySelector('#g').onclick=()=>{v=crypto.randomUUID();r.querySelector('#r').textContent=v};r.querySelector('#c').onclick=()=>copy(v)}},
gen:{name:'08 PASSWORD GEN',html:`<div class="grid"><div class="field"><label>Length</label><input id="l" type="number" value="20" min="8" max="128"></div><div class="field"><label>Count</label><input id="n" type="number" value="5" min="1" max="20"></div></div><div class="actions"><button class="btn" id="g">GENERATE</button><button class="btn alt" id="c">COPY</button></div><pre class="out" id="r"></pre>`,bind:r=>{let v='';r.querySelector('#g').onclick=()=>{let l=Math.min(128,Math.max(8,+r.querySelector('#l').value)),n=Math.min(20,Math.max(1,+r.querySelector('#n').value)),chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-+=',a=new Uint32Array(l*n);crypto.getRandomValues(a);v=Array.from({length:n},(_,i)=>Array.from({length:l},(_,j)=>chars[a[i*l+j]%chars.length]).join('')).join('\n');r.querySelector('#r').textContent=v};r.querySelector('#c').onclick=()=>copy(v)}},
notes:{name:'09 NOTES',html:`<div class="notice">Stored only in localStorage.</div><div class="field"><label>Notes</label><textarea id="n"></textarea></div><div class="actions"><button class="btn" id="s">SAVE</button><button class="btn alt" id="l">LOAD</button></div>`,bind:r=>{let n=r.querySelector('#n');r.querySelector('#s').onclick=()=>localStorage.setItem('cypherkit-notes',n.value);r.querySelector('#l').onclick=()=>n.value=localStorage.getItem('cypherkit-notes')||''}}
};
function render(k){nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.k===k));let t=tools[k];app.innerHTML=`<div class="card"><h3>${t.name}</h3>${t.html}</div>`;t.bind(app)}
Object.entries(tools).forEach(([k,t])=>{let b=document.createElement('button');b.className='nav';b.dataset.k=k;b.textContent=t.name;nav.appendChild(b)});
nav.onclick=e=>{let b=e.target.closest('button');if(b)render(b.dataset.k)};render('codec');setInterval(()=>document.querySelector('#clock').textContent=new Date().toLocaleTimeString([], {hour12:false}),1000);